# folder where the data is downloaded
data_root: /home/mtaktash/scratch/scannetpp

splits: [nvs_sem_train, nvs_sem_val]

# scene_ids: [07f5b601ee]
# scene_list_file: /home/mtaktash/scannetpp/ids.txt
scene_exclude_list_file: /home/mtaktash/scannetpp/exclude_ids_planar.txt

height: 390
width: 520