
# extract RGB frames
extract_rgb: true
# extract anonymization masks
extract_masks: true
# extract depth frames
extract_depth: false
# extract transforms.json
extract_nerfstudio_transforms: true

# cleanup the extracted images and masks after compressing them
cleanup_extracted: true

# folder where the data is downloaded
data_root: /home/mtaktash/scratch/scannetpp

splits: [nvs_sem_train, nvs_sem_val]

# scene_ids: [07f5b601ee]