# folder where the data is downloaded
data_root: /home/mtaktash/scratch/scannetpp

splits: [nvs_sem_train, nvs_sem_val]

# scene_ids: [07f5b601ee]
# scene_list_file: /home/mtaktash/scannetpp/ids.txt
scene_exclude_list_file: /home/mtaktash/scannetpp/exclude_ids_undistort.txt

# The following paths should be given relative to the DATA_ROOT/iphone/
# If not given, will use the default directory defined in ScannetppScene class

# input_image_dir: resized_images
# input_mask_dir: resized_anon_masks
# input_transforms_path: nerfstudio/transforms.json

# All use the relative path to DATA_ROOT/iphone/
out_image_dir: undistorted_images
out_mask_dir: undistorted_anon_masks
out_transforms_path: nerfstudio/transforms_undistorted.json
